/* empty css                          */
import { c as createAstro, d as createComponent, r as renderTemplate, g as renderComponent, m as maybeRenderHead } from '../astro_DOdjJ9xJ.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './carta_CzwDK3MZ.mjs';
/* empty css                             */

const $$Astro = createAstro();
const $$Contacto = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Contacto;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "El Rinc\xF3n del Bocata | Restaurante ", "data-astro-cid-2mxdoeuz": true }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<main class="mt-20 flex flex-col justify-center items-center gap-8" data-astro-cid-2mxdoeuz> <section class=" text-center" data-astro-cid-2mxdoeuz> <h2 class="my-4 font-semibold text-xl" data-astro-cid-2mxdoeuz>Pl. de Tetuan, 37, 12001 Castelló de la Plana, Castelló</h2> <button class="border-2 bg-orange-500 py-2 px-4 shadow-lg rounded-xl text-white text-lg" data-astro-cid-2mxdoeuz> <a title="Dirección El Rincón del Bocata" href="https://maps.app.goo.gl/dLZjSYj1CSbLducL7" target="_blank" rel="noopener noreferrer" data-astro-cid-2mxdoeuz>Ver en Google Maps</a> </button> </section> <section class=" text-center" data-astro-cid-2mxdoeuz> <h2 class="my-4 font-semibold text-xl" data-astro-cid-2mxdoeuz>Teléfono</h2> <button class="border-2 bg-orange-500 py-2 px-4 shadow-lg rounded-xl text-white text-lg" data-astro-cid-2mxdoeuz> <a title="Llamar al Rincón del Bocata" href="tel:964964964" rel="noopener noreferrer" data-astro-cid-2mxdoeuz>Llamar</a> </button> <button class="border-2 bg-orange-500 py-2 px-4 shadow-lg rounded-xl text-white text-lg" data-astro-cid-2mxdoeuz> <a href="whatsapp://send?&phone=+34964964964" data-astro-cid-2mxdoeuz>Whatsapp</a> </button> </section> <section class=" text-center" data-astro-cid-2mxdoeuz> <h2 class="my-4 font-semibold text-xl" data-astro-cid-2mxdoeuz>Horario</h2> <div class="flex justify-between min-w-80 px-4" data-astro-cid-2mxdoeuz> <p data-astro-cid-2mxdoeuz>Lunes: </p> <p class="text-red-500" data-astro-cid-2mxdoeuz>Cerrado</p> </div> <div class="flex justify-between min-w-80 px-4" data-astro-cid-2mxdoeuz> <p data-astro-cid-2mxdoeuz>Martes a Sábado: </p> <p data-astro-cid-2mxdoeuz>8:30 - 24:00</p> </div> <div class="flex justify-between min-w-80 px-4" data-astro-cid-2mxdoeuz> <p data-astro-cid-2mxdoeuz>Domingo:</p> <p data-astro-cid-2mxdoeuz>8:30 - 17:00</p> </div> </section> <section class=" text-center" data-astro-cid-2mxdoeuz> <h2 class="my-4 font-bold" data-astro-cid-2mxdoeuz>Síguenos en redes sociales:</h2> <div class="flex gap-4 justify-center my-2" data-astro-cid-2mxdoeuz> <a class="cursor-pointer hover:scale-105 transition" href="https://es-es.facebook.com/elrincondelbocata/" target="_blank" rel="noreferrer" data-astro-cid-2mxdoeuz> <img class="size-8" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/2021_Facebook_icon.svg/220px-2021_Facebook_icon.svg.png" alt="" data-astro-cid-2mxdoeuz> </a> <a class="cursor-pointer hover:scale-105 transition" href="https://www.instagram.com/explore/locations/413751147/el-rincon-del-bocata/" data-astro-cid-2mxdoeuz> <img class="size-8" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/1200px-Instagram_logo_2022.svg.png" alt="" data-astro-cid-2mxdoeuz> </a> </div> </section> </main> ` })} `;
}, "C:/Users/Soare/Desktop/rincon-aproach2/src/pages/contacto.astro", void 0);

const $$file = "C:/Users/Soare/Desktop/rincon-aproach2/src/pages/contacto.astro";
const $$url = "/contacto";

export { $$Contacto as default, $$file as file, $$url as url };
